### ISSUE TITLE
High nominals

### ISSUE THREAD

**Issue by BasilisAndr** [BasilisAndr/chkchn#1]
To Michael and Masha: existing Uniparser paradigms do not cover high animate inflection, as doesn't the lexicon. High animates is a pretty closed class, so maybe someone has a list of these nouns? Kinship terms, maybe some names from the mythology, considering that we will be dealing with fairytales.

**Comment by BasilisAndr** [comment]
@evoling

**Comment by evoling** [comment]
I don't have a list of high animates, and it's probably not possible to provide, since it's quite a fluid class. The kin terms only appear in high animate when they are used as address terms. I have examples of alternation between high animate and regular inflections within a single utterance. This is discussed in my dissertation p103-104.

**Comment by BasilisAndr** [comment]
Oh. Ok, we'll have to overgenerate then.

**Comment by BasilisAndr** [comment]
Oh. Ok, it seems that we'll have to overgenerate then.

**Comment by evoling** [comment]
Can we close this issue then?
